@ECHO OFF

SETLOCAL ENABLEEXTENSIONS ENABLEDELAYEDEXPANSION

:: variables
PUSHD "%~dp0" >NUL && SET CWD=%CD% && POPD >NUL

SET CONTAINER_NAME="mlaccetti-liquibase"
SET REFERENCE_DB_CONTAINER="some_postgresql_container"
SET LIQUIBASE_CHANGELOGS="%PWD%/db/changelog"
SET LIQUIBASE_CHANGELOG_FILE="db.changelog.postgresql.sql"
SET DB_CONNECTION_USERNAME="username"
SET DB_CONNECTION_PASSWORD="password"
SET DB_CONNECTION_HOST="db"
SET DB_CONNECTION_PORT="5432"
SET DB_CONNECTION_NAME="some-db"
SET DB_SCHEMA_NAME="public"
SET DIFF_TYPES="data"

docker run -it --rm ^
  --name %CONTAINER_NAME% ^
  --link %REFERENCE_DB_CONTAINER%:db ^
  -e DB_CONNECTION_USERNAME="%DB_CONNECTION_USERNAME%" ^
  -e DB_CONNECTION_PASSWORD="%DB_CONNECTION_PASSWORD%" ^
  -e DB_CONNECTION_HOST="%DB_CONNECTION_HOST%" ^
  -e DB_CONNECTION_PORT="%DB_CONNECTION_PORT%" ^
  -e DB_CONNECTION_NAME="%DB_CONNECTION_NAME%" ^
  -v /%LIQUIBASE_CHANGELOGS%:/changelogs ^
  -e DB_SCHEMA_NAME=%DB_SCHEMA_NAME% ^
  -e DIFF_TYPES=%DIFF_TYPES% ^
  mlaccetti/liquibase ^
  "generate"
